name: 'Main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  changesets:
    name: 'Changesets ğŸ¦‹'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: 'ğŸ”‘ Checkout'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'ğŸ° Setup Bun'
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest
          registries: |
            https://registry.npmjs.org

      - name: 'Install Dependencies'
        run: bun install

      - name: 'Pull Request || Publish'
        id: changeset
        uses: changesets/action@main
        with:
          publish: bun changeset:publish
          version: bun changeset:version
          title: 'chore: version package'
          commit: 'chore: version package'
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
